"""user update migration

Revision ID: 866470422d7f
Revises: 0beb7232032a
Create Date: 2024-09-12 21:12:37.320753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866470422d7f'
down_revision = '0beb7232032a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
